import { ref, watch } from 'vue'

const savedLang = localStorage.getItem('preferredLanguage') || 'en'

export const currentLang = ref<string>(savedLang)

watch(currentLang, (newLang: string) => {
  localStorage.setItem('preferredLanguage', newLang)
})

export const translations: Record<string, Record<string, string>> = {
  en: {
    home: 'Home',
    directory: 'Directory',
    projects: 'Projects',
    media: 'Media',
    login: 'Log in',
    dashboardUser: 'User Dashboard',
    welcome: 'Welcome',
    myProjects: 'My Projects',
    addNewProject: 'Add New Project',
    status: 'Status',
    action: 'Actions',
    heroTitle: 'Information Technology',
    heroSubtitle: 'Batch 2026 • President University',
    heroDesc: 'Empowering the future through technology, innovation, and leadership. Discover our journey, our projects, and our people.',
    btnMeet: 'Meet the Batch',
    btnView: 'View Projects',
    visionLabel: 'OUR VISION',
    visionTitle: 'Shaping the Digital World',
    visionDesc: 'We are a community of passionate developers, designers, and engineers dedicated to solving real-world problems.',
    card1Title: 'Technical Excellence',
    card1Desc: 'Mastering modern frameworks, algorithms, and software architectures to build robust solutions.',
    card2Title: 'Innovation First',
    card2Desc: 'Pushing boundaries and adopting cutting-edge technologies to stay ahead of the curve.',
    card3Title: 'Strong Community',
    card3Desc: 'Collaborating, learning together, and building a supportive network that lasts beyond graduation.',
    dirTitle: 'Student Directory',
    dirSubtitle: 'Explore the profiles and portfolios of Information Technology batch 2026 students.',
    dirSearchPlaceholder: 'Type to search (Name, NIM, Skill)...',
    
    projTitle: 'Our Projects',
    
    mediaTitle: 'Media Gallery',
    mediaSubtitle: 'A collection of event documentation and memories of IT Batch 2026.',

    adminDashboard: "Admin Dashboard",
    projectApprovalQueue: "Project Approval Queue",
    publishedProjects: "Published Projects",
    date: "Date",
    projectTitle: "Project Title",
    teamName: "Team Name",
    actions: "Actions",
    approve: "Approve",
    reject: "Reject",
    noPendingProjects: "No pending projects.",
    noPublishedProjects: "No published projects yet.",

    // profile
    title: "Informatics Department, President University",
    subtitle: "Preparing students to become industry-ready professionals in the digital era with a comprehensive and globally competitive curriculum.",
    heading: "About Us",
    parOne: "The Informatics Study Program at President University is designed to prepare students to become industry-ready professionals in the digital era. Unlike conventional programs, Informatics at President University integrates academic learning with intensive bootcamp programs, ensuring that students gain not only strong theoretical foundations but also real-world technical experience through case-based projects from industry partners.",
    parTwo: "This program offers five future-oriented concentrations: Artificial Intelligence, Internet of Things, Cyber Security, Game Development, and DevOps & Cloud Computing. Each concentration is directly aligned with global technology trends and is supported by hands-on bootcamps, collaborative team projects, and applied laboratories.",
    headingFacts: "Three Key Facts About the Program",
    factOne: `Internationally Accredited: `,
    oneCont: `The program is accredited by IABEE and holds an "Unggul" status from LAMINFOKOM, guaranteeing global academic standards and graduate quality.`,
    factTwo: "English-Based Learning Environment:",
    twoCont: "All courses are delivered fully in English, preparing graduates for international careers and multinational companies.",
    factThree: "Industry-Integrated Curriculum: ",
    threeCont: "Learning is reinforced through bootcamps, industry visits, collaborative projects, and internship programs, ensuring that students master both hard skills and professional work culture.",
    duration: "Duration",
    degree: "Degree",
    accreditation: "Accreditation",
    headCur: "Academics & Curriculum",
    badge: "Total Credits: 144 SKS",
    coreHeading: "Core Courses Highlight",
    coreOne: "Programming Concepts & Data Structure",
    coreTwo: "Web & Mobile Application Development",
    coreThree: "Artificial Intelligence & Machine Learning",
    coreFour: "Database System & Software Engineering",
    coreFive: "Computer Network & Security",
    coreSix: "Gen-AI and Internship Experience",
    
    concHeading: "5 Key Concentrations",
    concOne: "Artificial Intelligence:",
    oneConc: "NLP, Computer Vision, Deep Learning",
    concTwo: "Internet of Things:",
    twoConc: "Robotics, Embedded Systems",
    concThree: "Cyber Security:",
    threeConc: "Ethical Hacking, Digital Forensics",
    concFour: "Game Development:",
    fourConc: "Game Assets, XR, AI for Games",
    concFive: "DevOps & Cloud:",
    foveConc: "CI/CD, Containerization, Automation",

    // Facilities & Learning Hubs
    facHeading: "Facilities & Learning Hubs",
    facSmartTitle: "Smart Classrooms",
    facSmartDesc: "Equipped with high-speed internet access, interactive projectors, and advanced learning management systems.",
    facLabTitle: "Advanced Laboratories",
    facLabDesc: "Specialized labs for AI & Data Analytics (GPU-based systems), IoT & Robotics (sensors, microcontrollers), and Game Dev (VR/AR devices).",
    facHubTitle: "Innovation Hubs",
    facHubDesc: "Startup Incubation Space for business pitching and project rooms for bootcamp activities and capstone collaborations.",
    facIndTitle: "Industry Engagement",
    facIndDesc: "Direct exposure to professional technology environments through partner companies located within the Jababeka Industrial Estate.",

    // Our Lecturers
    lecHeading: "Our Lecturers",
    lecSubtitle: "Experts and practitioners ready to guide your creativity and sharpen your technical expertise.",
    lecHeadRole: "Head of Study Program",
    lecFullRole: "Full-Time Lecturer",

    // Career Impact
    careerHeading: "Career Impact",
    careerSubtitle: "After graduating from President University, students may choose to work in highly demanded professional roles such as:",
    careerRole1: "Professional IT",
    careerRole2: "Data Scientist",
    careerRole3: "Professional Programmer",
    careerRole4: "Cloud Architect Specialist",
    careerRole5: "Database Engineer",
    careerRole6: "Cyber Security Investigator",
    careerRole7: "Network and Security Specialist",
    careerRole8: "Digital Forensic Analyst",
    careerRole9: "Multimedia Designer and Animator",
    careerRole10: "IoT Architects",
    careerRole11: "IT Manager",
    careerRole12: "Technopreneur",
    careerRole13: "Researcher and Scientist",
  },
  id: {
    home: 'Beranda',
    directory: 'Direktori',
    projects: 'Proyek',
    media: 'Media',
    login: 'Masuk',
    dashboardUser: 'Dasbor Pengguna',
    welcome: 'Selamat Datang',
    myProjects: 'Proyek Saya',
    addNewProject: 'Tambah Proyek Baru',
    status: 'Status',
    action: 'Aksi',
    heroTitle: 'Teknologi Informasi',
    heroSubtitle: 'Angkatan 2026 • President University',
    heroDesc: 'Memberdayakan masa depan melalui teknologi, inovasi, dan kepemimpinan. Temukan perjalanan kami, proyek kami, dan komunitas kami.',
    btnMeet: 'Temui Angkatan',
    btnView: 'Lihat Proyek',
    visionLabel: 'VISI KAMI',
    visionTitle: 'Membentuk Dunia Digital',
    visionDesc: 'Kami adalah komunitas pengembang, desainer, dan insinyur penuh semangat yang berdedikasi untuk memecahkan masalah dunia nyata.',
    card1Title: 'Keunggulan Teknis',
    card1Desc: 'Mengusai framework modern, algoritma, dan arsitektur perangkat lunak untuk membangun solusi yang tangguh.',
    card2Title: 'Inovasi Utama',
    card2Desc: 'Menembus batas dan mengadopsi teknologi mutakhir untuk tetap menjadi yang terdepan.',
    card3Title: 'Komunitas yang Kuat',
    card3Desc: 'Berkolaborasi, belajar bersama, dan membangun jaringan suportif yang bertahan melampaui kelulusan.',
    dirTitle: 'Direktori Mahasiswa',
    dirSubtitle: 'Jelajahi profil dan portofolio mahasiswa Information Technology angkatan 2026.',
    dirSearchPlaceholder: 'Ketik untuk mencari (Nama, NIM, Keahlian)...',
    
    projTitle: 'Proyek Kami',
    
    mediaTitle: 'Galeri Media',
    mediaSubtitle: 'Kumpulan dokumentasi kegiatan dan memori IT Batch 2026.',

    adminDashboard: "Dashboard Admin",
    projectApprovalQueue: "Antrean Persetujuan Proyek",
    publishedProjects: "Proyek yang Diterbitkan",
    date: "Tanggal",
    projectTitle: "Judul Proyek",
    teamName: "Nama Tim",
    actions: "Aksi",
    approve: "Setujui",
    reject: "Tolak",
    noPendingProjects: "Tidak ada proyek yang menunggu.",
    noPublishedProjects: "Belum ada proyek yang diterbitkan.",

    // profile
    title: "Departemen Informatika, President University",
    subtitle: "Mempersiapkan mahasiswa menjadi profesional siap industri di era digital dengan kurikulum yang komprehensif dan berdaya saing global.",
    heading: "Tentang Kami",
    parOne: "Program Studi Informatika di President University dirancang untuk mempersiapkan mahasiswa menjadi profesional yang siap terjun ke industri di era digital. Berbeda dengan program konvensional, Informatika di President University mengintegrasikan pembelajaran akademik dengan program bootcamp intensif, memastikan mahasiswa tidak hanya mendapatkan fondasi teoretis yang kuat tetapi juga pengalaman teknis dunia nyata melalui proyek berbasis studi kasus dari mitra industri.",
    parTwo: "Program ini menawarkan lima konsentrasi berorientasi masa depan: Kecerdasan Buatan (AI), Internet of Things (IoT), Keamanan Siber, Pengembangan Gim, dan DevOps & Komputasi Awan. Setiap konsentrasi diselaraskan langsung dengan tren teknologi global dan didukung oleh bootcamp praktik langsung, proyek tim kolaboratif, dan laboratorium terapan.",
    headingFacts: "Tiga Fakta Utama Tentang Program Ini",
    factOne: `Terakreditasi Internasional: `,
    oneCont: `Program ini diakreditasi oleh IABEE dan memegang status "Unggul" dari LAMINFOKOM, menjamin standar akademik global dan kualitas lulusan.`,
    factTwo: "Lingkungan Belajar Berbasis Bahasa Inggris: Semua mata kuliah disampaikan sepenuhnya dalam bahasa Inggris, mempersiapkan lulusan untuk karier internasional dan perusahaan multinasional.",
    twoCont: `Semua mata kuliah disampaikan sepenuhnya dalam bahasa Inggris, mempersiapkan lulusan untuk karier internasional dan perusahaan multinasional.`,
    factThree: "Kurikulum Terintegrasi Industri: ",
    threeCont: `Pembelajaran diperkuat melalui bootcamp, kunjungan industri, proyek kolaboratif, dan program magang, memastikan mahasiswa menguasai keterampilan teknis (hard skills) dan budaya kerja profesional.`,
    duration: "Durasi",
    degree: "Gelar",
    accreditation: "Akreditasi",
    headCur: "Akademik & Kurikulum",
    badge: "Total SKS: 144 SKS",
    coreHeading: "Sorotan Mata Kuliah Inti",
    coreOne: "Konsep Pemrograman & Struktur Data",
    coreTwo: "Pengembangan Aplikasi Web & Seluler",
    coreThree: "Kecerdasan Buatan & Pembelajaran Mesin",
    coreFour: "Sistem Basis Data & Rekayasa Perangkat Lunak",
    coreFive: "Jaringan Komputer & Keamanan",
    coreSix: "Gen-AI dan Pengalaman Magang",
    
    concHeading: "5 Konsentrasi Utama",
    concOne: "Kecerdasan Buatan:",
    oneConc: "NLP, Visi Komputer, Pembelajaran Mendalam",
    concTwo: "Internet of Things: ",
    twoConc: "Robotika, Sistem Tertanam",
    concThree: "Keamanan Siber: ",
    threeConc: "Peretasan Etis, Forensik Digital",
    concFour: "Pengembangan Gim: ",
    fourConc: "Aset Gim, XR, AI untuk Gim",
    concFive: "DevOps & Cloud: ",
    fiveConc: "CI/CD, Kontainerisasi, Otomasi",

    // Facilities & Learning Hubs
    facHeading: "Fasilitas & Pusat Pembelajaran",
    facSmartTitle: "Kelas Pintar",
    facSmartDesc: "Dilengkapi dengan akses internet berkecepatan tinggi, proyektor interaktif, dan sistem manajemen pembelajaran tingkat lanjut.",
    facLabTitle: "Laboratorium Lanjutan",
    facLabDesc: "Lab khusus untuk AI & Analitik Data (sistem berbasis GPU), IoT & Robotika (sensor, mikrokontroler), dan Pengembangan Gim (perangkat VR/AR).",
    facHubTitle: "Pusat Inovasi",
    facHubDesc: "Ruang Inkubasi Startup untuk presentasi bisnis dan ruang proyek untuk aktivitas bootcamp serta kolaborasi capstone.",
    facIndTitle: "Keterlibatan Industri",
    facIndDesc: "Paparan langsung terhadap lingkungan teknologi profesional melalui perusahaan mitra yang berlokasi di dalam Kawasan Industri Jababeka.",

    // Our Lecturers
    lecHeading: "Dosen Kami",
    lecSubtitle: "Para pakar dan praktisi yang siap membimbing kreativitas dan mengasah keahlian teknis Anda.",
    lecHeadRole: "Kepala Program Studi",
    lecFullRole: "Dosen Tetap",

    // Career Impact
    careerHeading: "Dampak Karier",
    careerSubtitle: "Setelah lulus dari President University, mahasiswa dapat memilih untuk bekerja di peran profesional yang sangat diminati seperti:",
    careerRole1: "Profesional TI",
    careerRole2: "Ilmuwan Data",
    careerRole3: "Pemrogram Profesional",
    careerRole4: "Spesialis Arsitek Cloud",
    careerRole5: "Insinyur Basis Data",
    careerRole6: "Penyelidik Keamanan Siber",
    careerRole7: "Spesialis Jaringan dan Keamanan",
    careerRole8: "Analis Forensik Digital",
    careerRole9: "Desainer dan Animator Multimedia",
    careerRole10: "Arsitek IoT",
    careerRole11: "Manajer TI",
    careerRole12: "Teknopreneur",
    careerRole13: "Peneliti dan Ilmuwan",
  },
  zh: {
    home: '首页',
    directory: '名录',
    projects: '项目',
    media: '媒体',
    login: '登录',
    dashboardUser: '用户仪表板',
    welcome: '欢迎',
    myProjects: '我的项目',
    addNewProject: '添加新项目',
    status: '状态',
    action: '操作',
    heroTitle: '信息技术', heroSubtitle: '2026届 • 总统大学', heroDesc: '通过技术、创新和领导力赋能未来。探索我们的历程、项目和团队。',
    btnMeet: '认识团队', btnView: '查看项目', visionLabel: '我们的愿景', visionTitle: '塑造数字世界',
    visionDesc: '我们是一个由充满热情的开发人员、设计师和工程师组成的 community，致力于解决现实世界的问题。',
    card1Title: '卓越技术', card1Desc: '掌握现代框架、算法和软件架构,以构建强大的解决方案。',
    card2Title: '创新第一', card2Desc: '突破界限并采用尖端技术,保持领先地位。',
    card3Title: '强大的社区', card3Desc: '通力合作、共同学习,并建立一个延续到毕业以后的支持性网络。',
    dirTitle: '学生名录',
    dirSubtitle: '探索 2026 届信息技术专业学生的个人资料和作品集。',
    dirSearchPlaceholder: '输入以搜索 (姓名, 学号, 技能)...',
    
    projTitle: '我们的项目',
    
    mediaTitle: '媒体库',
    mediaSubtitle: '2026 届 IT 专业活动记录与回忆集锦。',

    adminDashboard: "管理员仪表板",
    projectApprovalQueue: "项目审批队列",
    publishedProjects: "已发布项目",
    date: "日期",
    projectTitle: "项目名称",
    teamName: "团队名称",
    actions: "操作",
    approve: "批准",
    reject: "拒绝",
    noPendingProjects: "没有待处理的项目。",
    noPublishedProjects: "暂无已发布的项目。",

    // profile
    title: "信息学系, 总统大学",
    subtitle: "以全面且具有全球竞争力的课程，培养学生成为数字时代适应工业需求的专业人才。",
    heading: "关于我们",
    parOne: "总统大学信息学专业旨在培养学生成为数字时代适应工业需求的专业人才。与传统项目不同，总统大学信息学系将学术学习与密集的新兵训练营（bootcamp）项目相结合，确保学生不仅获得扎实的理论基础，还通过来自行业合作伙伴的真实案例项目获得实际的技术经验。",
    parTwo: "该项目提供五个面向未来的专业方向：人工智能、物联网、网络安全、游戏开发以及DevOps与云计算。每个方向都直接与全球技术趋势接轨，并由实操训练营、团队协作项目和应用实验室提供支持。",
    headingFacts: "关于本专业的三个关键事实",
    factOne: `国际认证：`,
    oneCont: `该项目获得IABEE认证，并获得LAMINFOKOM的“优秀 (Unggul)”评级，确保了全球学术标准和毕业生质量。`,
    factTwo: "全英文学习环境：",
    twoCont: `所有课程均以全英文授课，为毕业生应对国际职业生涯和跨国公司做好准备。`,
    factThree: "产教融合课程：",
    threeCont: `通过训练营、企业参观、合作项目和实习项目加强学习，确保学生掌握硬技能和专业工作文化。`,
    duration: "学制",
    degree: "学位",
    accreditation: "认证",
    headCur: "学术与课程",
    badge: "总学分：144 SKS",
    coreHeading: "核心课程亮点",
    coreOne: "编程概念与数据结构",
    coreTwo: "Web与移动应用开发",
    coreThree: "人工智能与机器学习",
    coreFour: "数据库系统与软件工程",
    coreFive: "计算机网络与安全",
    coreSix: "生成式AI与实习经验",
    
    concHeading: "5大核心专业方向",
    concOne: "人工智能: ",
    oneConc: "自然语言处理 (NLP)，计算机视觉，深度学习",
    concTwo: "物联网: ",
    twoConc: "机器人技术，嵌入式系统",
    concThree: "网络安全: ",
    threeConc: "道德黑客，数字取证",
    concFour: "游戏开发: ",
    fourConc: "游戏资产，扩展现实 (XR)，游戏AI",
    concFive: "DevOps与云: ",
    fiveConc: "持续集成/持续交付 (CI/CD)，容器化，自动化",

    // Facilities & Learning Hubs
    facHeading: "设施与学习中心",
    facSmartTitle: "智能教室",
    facSmartDesc: "配备高速互联网接入、交互式投影仪和先进的学习管理系统。",
    facLabTitle: "高级实验室",
    facLabDesc: "专门用于人工智能与数据分析（基于GPU的系统）、物联网与机器人（传感器、微控制器）以及游戏开发（VR/AR设备）的实验室。",
    facHubTitle: "创新中心",
    facHubDesc: "用于商业路演的初创企业孵化空间，以及用于训练营活动和毕业设计合作的项目室。",
    facIndTitle: "行业互动",
    facIndDesc: "通过位于Jababeka工业区内的合作企业，直接接触专业技术环境。",

    // Our Lecturers
    lecHeading: "我们的讲师",
    lecSubtitle: "专家和从业人员随时准备指导您的创造力并磨练您的专业技术。",
    lecHeadRole: "专业负责人",
    lecFullRole: "全职讲师",

    // Career Impact
    careerHeading: "职业影响",
    careerSubtitle: "从总统大学毕业后，学生可以选择从事高需求专业岗位，例如：",
    careerRole1: "专业IT人员",
    careerRole2: "数据科学家",
    careerRole3: "专业程序员",
    careerRole4: "云架构专家",
    careerRole5: "数据库工程师",
    careerRole6: "网络安全调查员",
    careerRole7: "网络与安全专家",
    careerRole8: "数字取证分析师",
    careerRole9: "多媒体设计师和动画师",
    careerRole10: "物联网架构师",
    careerRole11: "IT经理",
    careerRole12: "科技创业者",
    careerRole13: "研究员和科学家",
  },
  ko: {
    home: '홈',
    directory: '디렉토리',
    projects: '프로젝트',
    media: '미디어',
    login: '로그인',
    dashboardUser: '사용자 대시보드',
    welcome: '환영합니다',
    myProjects: '내 프로젝트',
    addNewProject: '새 프로젝트 추가',
    status: '상태',
    action: '작업',
    heroTitle: '정보 기술', heroSubtitle: '2026 학번 • 프레지던트 대학교', heroDesc: '기술, 혁신, 리더십을 통해 미래를 주도합니다. 우리의 여정, 프로젝트, 그리고 사람들을 만나보세요.',
    btnMeet: '동기들 만나기', btnView: '프로젝트 보기', visionLabel: '우리의 비전', visionTitle: '디지털 세계를 형성하다',
    visionDesc: '우리는 실제 문제를 해결하기 위해 헌신하는 열정적인 개발자, 디자이너, 엔지니어들의 커뮤니티입니다.',
    card1Title: '기술적 탁월함', card1Desc: '최신 프레임워크, 알고리즘, 소프트웨어 아키텍처를 마스터하여 견고한 솔루션을 구축합니다.',
    card2Title: '혁신 우선', card2Desc: '한계를 뛰어넘고 최첨단 기술을 도입하여 앞서 나갑니다.',
    card3Title: '강력한 커뮤니티', card3Desc: '협력하고 함께 배우며, 졸업 후에도 지속되는 지원 네트워크를 형성합니다.',
    dirTitle: '학생 디렉토리',
    dirSubtitle: '2026 학번 정보 기술 학생들의 프로필과 포트폴리오를 탐색해보세요.',
    dirSearchPlaceholder: '검색어 입력 (이름, 학번, 기술)...',
    
    projTitle: '우리의 프로젝트',
    
    mediaTitle: '미디어 갤러리',
    mediaSubtitle: 'IT 2026 학번의 행사 기록 및 추억 모음.',

    adminDashboard: "관리자 대시보드",
    projectApprovalQueue: "프로젝트 승인 대기열",
    publishedProjects: "게시된 프로젝트",
    date: "날짜",
    projectTitle: "프로젝트 제목",
    teamName: "팀 이름",
    actions: "작업",
    approve: "승인",
    reject: "거절",
    noPendingProjects: "대기 중인 프로젝트가 없습니다.",
    noPublishedProjects: "게시된 프로젝트가 없습니다.",

    // profile
    title: "정보학과, 프레지던트 대학교",
    subtitle: "포괄적이고 글로벌 경쟁력을 갖춘 커리큘럼을 통해 디지털 시대에 산업 요구에 부응하는 전문가로 학생들을 양성합니다.",
    heading: "소개",
    parOne: "프레지던트 대학교의 정보학 전공은 디지털 시대에 산업에 즉각 투입할 수 있는 전문가를 양성하도록 설계되었습니다. 기존 프로그램과 달리, 프레지던트 대학교의 정보학은 학문적 학습과 집중적인 부트캠프 프로그램을 통합하여, 학생들이 탄탄한 이론적 기초뿐만 아니라 산업 파트너의 사례 기반 프로젝트를 통해 실제 기술 경험을 얻을 수 있도록 보장합니다.",
    parTwo: "이 프로그램은 인공지능, 사물인터넷(IoT), 사이버 보안, 게임 개발, DevOps 및 클라우드 컴퓨팅 등 5가지 미래 지향적인 세부 전공을 제공합니다. 각 세부 전공은 글로벌 기술 트렌드와 직접적으로 일치하며, 실습 위주의 부트캠프, 협업 팀 프로젝트 및 응용 연구실의 지원을 받습니다.",
    headingFacts: "프로그램에 대한 3가지 주요 사실",
    factOne: `국제 인증: `,
    oneCont: `이 프로그램은 IABEE의 인증을 받았으며 LAMINFOKOM으로부터 "최우수(Unggul)" 등급을 받아 글로벌 학사 표준과 졸업생의 질을 보장합니다.`,
    factTwo: "영어 기반 학습 환경: ",
    twoCont: `모든 과정은 100% 영어로 진행되어 졸업생들이 국제적인 커리어와 다국적 기업에서 일할 수 있도록 준비시킵니다.`,
    factThree: "산업 통합 커리큘럼: ",
    threeCont: `부트캠프, 산업체 견학, 협업 프로젝트 및 인턴십 프로그램을 통해 학습이 강화되며, 학생들이 하드 스킬과 전문적인 직장 문화를 모두 마스터할 수 있도록 보장합니다.`,
    duration: "기간",
    degree: "학위",
    accreditation: "인증",
    headCur: "학사 및 커리큘럼",
    badge: "총 학점: 144 SKS",
    coreHeading: "핵심 과정 하이라이트",
    coreOne: "프로그래밍 개념 및 자료 구조",
    coreTwo: "웹 및 모바일 애플리케이션 개발",
    coreThree: "인공지능 및 기계 학습",
    coreFour: "데이터베이스 시스템 및 소프트웨어 공학",
    coreFive: "컴퓨터 네트워크 및 보안",
    coreSix: "생성형 AI 및 인턴십 경험",
    
    concHeading: "5대 핵심 세부 전공",
    concOne: "인공지능: ",
    oneConc: "자연어 처리(NLP), 컴퓨터 비전, 딥 러닝",
    concTwo: "사물인터넷(IoT): ",
    twoConc: "로봇 공학, 임베디드 시스템",
    concThree: "사이버 보안: ",
    threeConc: "윤리적 해킹, 디지털 포렌식",
    concFour: "게임 개발: ",
    fourConc: "게임 에셋, 확장 현실(XR), 게임용 AI",
    concFive: "DevOps 및 클라우드: ",
    fiveConc: "CI/CD, 컨테이너화, 자동화",

    // Facilities & Learning Hubs
    facHeading: "시설 및 학습 허브",
    facSmartTitle: "스마트 강의실",
    facSmartDesc: "초고속 인터넷망, 대화형 프로젝터 및 첨단 학습 관리 시스템을 갖추고 있습니다.",
    facLabTitle: "첨단 연구실",
    facLabDesc: "AI 및 데이터 분석(GPU 기반 시스템), IoT 및 로봇 공학(센서, 마이크로컨트롤러), 게임 개발(VR/AR 기기)을 위한 특수 연구실입니다.",
    facHubTitle: "혁신 허브",
    facHubDesc: "비즈니스 피칭을 위한 스타트업 인큐베이션 공간과 부트캠프 활동 및 캡스톤 협업을 위한 프로젝트룸입니다.",
    facIndTitle: "산업 참여",
    facIndDesc: "자바베카(Jababeka) 산업 단지 내에 위치한 파트너 기업을 통해 전문적인 기술 환경을 직접 경험할 수 있습니다.",

    // Our Lecturers
    lecHeading: "교수진",
    lecSubtitle: "여러분의 창의력을 이끌고 기술적 전문성을 연마하도록 지도할 준비가 된 전문가 및 실무자들입니다.",
    lecHeadRole: "학과장",
    lecFullRole: "전임 강사",

    // Career Impact
    careerHeading: "커리어 임팩트",
    careerSubtitle: "프레지던트 대학교 졸업 후, 학생들은 다음과 같이 수요가 높은 전문 직종을 선택하여 일할 수 있습니다:",
    careerRole1: "전문 IT 인력",
    careerRole2: "데이터 과학자",
    careerRole3: "전문 프로그래머",
    careerRole4: "클라우드 아키텍트 전문가",
    careerRole5: "데이터베이스 엔지니어",
    careerRole6: "사이버 보안 조사관",
    careerRole7: "네트워크 및 보안 전문가",
    careerRole8: "디지털 포렌식 애널리스트",
    careerRole9: "멀티미디어 디자이너 및 애니메이터",
    careerRole10: "IoT 아키텍트",
    careerRole11: "IT 매니저",
    careerRole12: "기술 창업가",
    careerRole13: "연구원 및 과학자",
  }
}